[versions]
# The Project version represents the snapshot version and must never be modified,
# as it is the release tag that indicates the release version.
project = "99.99.99"
# Dependencies versions
agp = "8.10.1"
androidxActivity = "1.10.1"
androidxActivityCompose = "1.10.1"
androidxAppcompat = "1.7.1"
androidxConstraintLayout = "2.2.1"
androidxCore = "1.16.0"
androidxDatastorePreferences = "1.1.7"
androidxFragment = "1.8.8"
androidxLifecycleViewmodel = "2.9.2"
androidxMultidex = "2.0.1"
androidxNavigationCompose = "2.9.0-rc01"
assertj = "3.25.3"
bitLib4j = "1.4.5"
compottie = "2.0.0"
composeBom = "2025.08.01"
composePlugin = "1.8.2"
coroutines = "1.10.2"
dagger = "2.25"
eventbus = "3.3.1"
glassfish = "10.0-b28"
gson = "2.11.0"
keypleJavaBom = "2025.12.12"
keyplePluginCnaCoppernicCone2Lib = "2.0.2"
keyplePluginCnaFamocoSeCommunicationLib = "2.0.2"
koin = "4.1.0"
kotlin = "2.2.10"
kotlinStdlibJdk8 = "1.7.22"
kotlinxSerializationCore = "1.9.0"
ktor = "3.2.3"
lottie = "3.4.4"
material = "1.12.0"
napier = "2.7.1"
okhttpLogging = "3.9.1"
quarkus = "1.8.1.Final"
retrofit = "2.11.0"
retrofitCompat = "2.11.0"
rxandroid = "2.1.1"
rxjava = "2.2.21"
slf4j = "1.7.32"
slf4jAndroid = "1.7.32-0"
spotless = "7.0.4"
timber = "5.0.1"

[libraries]
androidxActivity = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }
androidxActivityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityCompose" }
androidxAppcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidxConstraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstraintLayout" }
androidxCore = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidxDatastorePreferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidxDatastorePreferences" }
androidxFragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragment" }
androidxLifecycleViewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycleViewmodel" }
androidxMultidex = { module = "androidx.multidex:multidex", version.ref = "androidxMultidex" }
androidxNavigationCompose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidxNavigationCompose" }
assertjCore = { module = "org.assertj:assertj-core", version.ref = "assertj" }
bitLib4j = { module = "com.github.devnied:bit-lib4j", version.ref = "bitLib4j" }
compottieLite = { module = "io.github.alexzhirkevich:compottie-lite", version.ref = "compottie" }
compottieRes = { module = "io.github.alexzhirkevich:compottie-resources", version.ref = "compottie" }
composeBom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
daggerAndroid = { module = "com.google.dagger:dagger-android", version.ref = "dagger" }
daggerAndroidProcessor = { module = "com.google.dagger:dagger-android-processor", version.ref = "dagger" }
daggerAndroidSupport = { module = "com.google.dagger:dagger-android-support", version.ref = "dagger" }
daggerCompiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
glassfishAnnotations = { module = "org.glassfish:javax.annotation", version.ref = "glassfish" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
keypleJavaBom = { module = "org.eclipse.keyple:keyple-java-bom", version.ref = "keypleJavaBom" }
keypleCardCalypsoCryptoLegacysamLib = { module = "org.eclipse.keyple:keyple-card-calypso-crypto-legacysam-java-lib" }
keypleCardCalypsoCryptoPkiLib = { module = "org.eclipse.keyple:keyple-card-calypso-crypto-pki-java-lib" }
keypleCardCalypsoLib = { module = "org.eclipse.keyple:keyple-card-calypso-java-lib" }
keypleCommonApi = { module = "org.eclipse.keyple:keyple-common-java-api" }
keypleDistributedLocalLib = { module = "org.eclipse.keyple:keyple-distributed-local-java-lib" }
keypleDistributedNetworkLib = { module = "org.eclipse.keyple:keyple-distributed-network-java-lib" }
keypleDistributedRemoteLib = { module = "org.eclipse.keyple:keyple-distributed-remote-java-lib" }
keypleInteropJsonapiClientKmpLib = { module = "org.eclipse.keyple:keyple-interop-jsonapi-client-kmp-lib" }
keypleInteropLocalreaderNfcmobileKmpLib = { module = "org.eclipse.keyple:keyple-interop-localreader-nfcmobile-kmp-lib" }
keyplePluginAndroidNfcLib = { module = "org.eclipse.keyple:keyple-plugin-android-nfc-java-lib" }
keyplePluginAndroidOmapiLib = { module = "org.eclipse.keyple:keyple-plugin-android-omapi-java-lib" }
keyplePluginCnaCoppernicCone2Lib = { module = "org.calypsonet.keyple:keyple-plugin-cna-coppernic-cone2-java-lib", version.ref = "keyplePluginCnaCoppernicCone2Lib" }
keyplePluginCnaFamocoSeCommunicationLib = { module = "org.calypsonet.keyple:keyple-plugin-cna-famoco-se-communication-java-lib", version.ref = "keyplePluginCnaFamocoSeCommunicationLib" }
keyplePluginPcscLib = { module = "org.eclipse.keyple:keyple-plugin-pcsc-java-lib" }
keyplePluginStoragecardApi = { module = "org.eclipse.keyple:keyple-plugin-storagecard-java-api" }
keypleServiceLib = { module = "org.eclipse.keyple:keyple-service-java-lib" }
keypleServiceResourceLib = { module = "org.eclipse.keyple:keyple-service-resource-java-lib" }
keypleUtilJavaLib = { module = "org.eclipse.keyple:keyple-util-java-lib" }
keypopCalypsoCardApi = { module = "org.eclipse.keypop:keypop-calypso-card-java-api" }
keypopCalypsoCryptoLegacysamApi = { module = "org.eclipse.keypop:keypop-calypso-crypto-legacysam-java-api" }
keypopReaderApi = { module = "org.eclipse.keypop:keypop-reader-java-api" }
keypopStoragecardApi = { module = "org.eclipse.keypop:keypop-storagecard-java-api" }
koinAndroid = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koinAndroidxCompose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koinCompose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koinCore = { module = "io.insert-koin:koin-core", version.ref = "koin" }
kotlinStdlibJdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlinStdlibJdk8" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlinStdlibJdk8" }
kotlinxCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinxCoroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
kotlinxSerializationCore = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }
ktorClientAuth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktorClientCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktorClientContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktorClientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorClientDarwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktorClientLogging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktorClientOkhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktorSerializationKotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { module = "com.google.android.material:material", version.ref = "material" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
okhttpLoggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttpLogging" }
quarkusBom = { module = "io.quarkus:quarkus-universe-bom", version.ref = "quarkus" }
quarkusResteasy = { module = "io.quarkus:quarkus-resteasy" }
quarkusResteasyJsonb = { module = "io.quarkus:quarkus-resteasy-jsonb" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitAdapterRxjava2 = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "retrofitCompat" }
retrofitConverterGson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofitCompat" }
retrofitConverterScalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofitCompat" }
rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava" }
slf4jAndroid = { module = "uk.uuid.slf4j:slf4j-android", version.ref = "slf4jAndroid" }
slf4jApi = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4jSimple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "composePlugin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinStdlibJdk8" }
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
